#!/opt/imh-python/bin/python

import argparse
from subprocess import Popen
import arrow

def build_output_filename(rate, prefix=''):
    now = arrow.now().format('YYYY-MM-DD_HH:mm:ss')

    if prefix:
        return '{prefix}_r{rate}-{timestamp}'.format(rate=rate, prefix=prefix, timestamp=now)
    return 'r{rate}-{timestamp}'.format(rate=rate, timestamp=now)

def file_attack(target_file, duration, rate, step, max, prefix):
    for r in range(rate, max+step, step):
        cmd = 'vegeta attack -targets {} -duration {} -rate {} -output {output}'.format(target_file, duration, r, output=build_output_filename(r, prefix))
        Popen(cmd, shell=True).wait()

def target_attack(target_host, verb, duration, rate, step, max, prefix):
    for r in range(rate, max, step):
        cmd = 'echo "{} {}" | vegeta attack -duration {} -rate {} -output {output}'.format(verb, target_host, duration, r, output=build_output_filename(r, prefix))
        Popen(cmd, shell=True).wait()

def build_parser():
    parser = argparse.ArgumentParser(description='Vegeta convenience wrapper')

    tuning_parser = parser.add_argument_group('Request Tuning', 'These flags are optional and can be provided to change the quantiy/duration of test requests.')

    tuning_parser.add_argument('-d', '--duration', dest='duration', default=10)
    tuning_parser.add_argument('-r', '--rate', dest='rate', default=1000, type=int)
    tuning_parser.add_argument('-s', '--step', dest='step', default=10, type=int)
    tuning_parser.add_argument('-m', '--max', dest='max', default=10000, type=int)
    tuning_parser.add_argument('-p', '--prefix', dest='prefix', default='')

    target_parser = parser.add_argument_group('Target Files', 'This flag is used to specify a target file for your attack. Exclusive with Manual Target.')
    target_parser.add_argument('-f', '--file', dest='file', default=None)

    manual_parser = parser.add_argument_group('Manual Target', 'This flag allows you manually specify the target hostname and HTTP Verb. Exclusive with Target Files.')
    manual_parser.add_argument('-t', '--target', dest='target')
    manual_parser.add_argument('-v', '--verb', dest='verb', default='GET', type=lambda v:v.upper())

    return parser

def main(args):
    if args.file:
        file_attack(args.file, args.duration, args.rate, args.step, args.max, args.prefix)
    elif args.target:
        target_attack(args.target, args.verb, args.duration, args.rate, args.step, args.max, args.prefix)

if __name__ == '__main__':
    parser = build_parser()

    args = parser.parse_args()

    if args.file and args.target:
        raise ValueError('--file and --target are mutually exclusive and cannot be used together.')

    main(args)
