#!/bin/bash


incremental_test() {
    output_dir="$(dirname $4)_data"
    test_start=$(date +"%Y-%m-%d_%H-%M-%S")

    #read -p "Engintron? y/n" engine
    #TODO: Amend the output filename generation to include whether nginx or apache is handling the test.

    #Setting the max rate should be configurable, but I don't want to have too many command line parameters. env var maybe?
    while [ $rate -lt $maxrate ]; do 
        echo -e "REQUEST RATE: $rate per second\n"
        vegeta attack -targets $4 -duration $2 -rate $rate -output "$output_dir/$test_start"."$rate".bin
        let rate=$rate + $3

    #echo "$request http://$hostname" |./vegeta attack -duration $duration -rate 1
    done
}

function main() {
echo
#find ./tests/ -type f -exec incremental_test($1, $2, {}) \; 
#This is the gist of what I want. Go over tests one at a time and run through the increments.
#Also, help output would be nice, but not necessary.
}
